dropbox_dir: 'Y:\DROPBOX'
dropbox_link_dir: '\\OpR-Marc-RC2\Data\DROPBOX'
build_target: 'D:\Volumes'
overflow_build_target: 'W:\Volumes'
raw_data_dir: '\\OpR-Marc-Syn3\Data\RawData'
notification_dir: 'Y:\DROPBOX\Notification'
core_deployment_dir: 'X:\Volumes'
worker_threads: 6
process_tem_output: true
automatic_builds: true
junk_outputs:
  - Jobs Queued
  - underflow encountered in multiply
  - Ill-conditioned matrix
  - ImageStats.*ETA
fatal_errors:
  - need at most 63 handles
  - No output from ir-refine-grid
  - is not recognized as an internal or external command, operable program or batch file
  - No tiles found in IDoc
  - After removing missing file names there were no tiles remaining
  - expected one argument
  - OSError.*requested and 0 written
volumes:
  - name: RC3
    path: "W:/Volumes/RC3"
    save_raw_data: true
    import_script: "RC3Import"
    build_script: "RC3Build"
    optimize_tiles_script: "RC3OptimizeTiles"
    align_script: "RC3Align"