dropbox_dir: 'Y:\DROPBOX'
dropbox_link_dir: '\\OpR-Marc-RC2\Data\DROPBOX'
build_target: 'D:\Volumes'
python_env: 'C:\Python39\Scripts'
raw_data_dir: '\\OpR-Marc-Syn3\Data\RawData'
notification_dir: 'Y:\DROPBOX\Notification'
core_deployment_dir: 'X:\Volumes'
worker_threads: 2
process_tem_output: true
automatic_builds: true
fatal_errors:
  - need at most 63 handles