dropbox_dir: 'D:\DROPBOX'
dropbox_link_dir: '\\OpR-Marc-RC2\Data\DROPBOX'
build_target: 'W:\Volumes'
raw_data_dir: '\\OpR-Marc-Syn3\Data\RawData'
notification_dir: 'D:\DROPBOX\Notification'
core_deployment_dir: 'X:\Volumes'
worker_threads: 1
process_tem_output: false
automatic_builds: false
fatal_errors: []