* TEMmy

	TEMmy is an interactive electron microscope tutorial written using literate programming.
	
** Dependencies
	 
	 Most of the dependencies are included in this repository to keep their versions static.

	 You do need to install some of them separately: 

	 - Emacs, for compiling this file into a static website.
	 - Mono (if compiling on a non-windows platform), for running inklecate.exe

	 Parts of the build process are scripted in Bash, so building on Windows is not recommended.

*** Inkjs

		Inkjs is a re-implementation of [[http:www.inklestudios.com/ink/][Ink]], a scripting language for making choice-based games. The important parts of TEMmy are written in Ink because it is a simple language, and anyone should be able to update TEMmy's Ink logic by following this guide: [[http:github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md][Writing With Ink]].

		The Inkjs source code is governed by the MIT License, and its license file is included in the boilerplate directory.

*** Ink

		TEMmy is built using Inklecate, the official Ink compiler. Ink is governed by the MIT License, and its license file is included in the inklecate directory.

** Build

	 
	 
	 
	 
	 

